from typing import Any

PLATFORM_RULES: dict[str, dict[str, Any]] = {
    "instagram": {
        "id": "instagram",
        "name": "Instagram",
        "icon": "Instagram",
        "description": "Visual-first platform focused on aesthetic hooks, lifestyle storytelling, and strategic hashtags.",
        "char_limit": 2200,
        "includes_hashtags": True,
        "recommended_hashtags_count": 8,
        "includes_emojis": True,
        "requires_visual": True,
        "supported_media": ["image", "video", "text"],
        "content_style": "Hook in first 1-2 lines before 'more' fold. High aesthetic value, relatable storytelling, lively emoji spacing, strong CTA for comments/saves/shares.",
        "best_practices": [
            "Put the strongest hook in the first 80 characters",
            "Use line breaks to enhance readability",
            "Include 5-10 hyper-relevant niche hashtags",
            "Pair with high-contrast, scroll-stopping visual prompts",
        ],
        "output_requirements": "Hook, caption, CTA, 5-10 hashtags, emojis, image/video visual prompt.",
    },
    "tiktok": {
        "id": "tiktok",
        "name": "TikTok",
        "icon": "Video",
        "description": "Short-form vertical video platform driven by trends, immediate 3-second hooks, and viral audio cues.",
        "char_limit": 2200,
        "includes_hashtags": True,
        "recommended_hashtags_count": 5,
        "includes_emojis": True,
        "requires_visual": True,
        "supported_media": ["video", "text", "audio"],
        "content_style": "Hook viewers in the first 2-3 seconds with high pattern interruption, vertical 9:16 video script scenes, punchy caption, viral niche hashtags (#fyp, #trend).",
        "best_practices": [
            "Hook must interrupt scrolling in under 3 seconds",
            "Use fast-paced cutaways and dynamic on-screen text",
            "Include 3-5 trending and niche-specific hashtags",
        ],
        "output_requirements": "3-second viral hook, dynamic video script, caption, 3-5 hashtags, sound/audio suggestion.",
    },
    "facebook": {
        "id": "facebook",
        "name": "Facebook",
        "icon": "Facebook",
        "description": "Community and conversation-driven network with long-form storytelling and link-friendly copy.",
        "char_limit": 5000,
        "includes_hashtags": True,
        "recommended_hashtags_count": 3,
        "includes_emojis": True,
        "requires_visual": True,
        "supported_media": ["text", "image", "video"],
        "content_style": "Attention-grabbing opening, conversational community tone, storytelling paragraphs, clear CTA driving clicks or comments.",
        "best_practices": [
            "Ask questions to trigger community discussions",
            "Use minimal hashtags (1-3 max)",
            "Focus on relatable problem-solution storytelling",
        ],
        "output_requirements": "Attention-grabbing opening, main conversational body, clear CTA, 1-3 hashtags, media prompt.",
    },
    "youtube": {
        "id": "youtube",
        "name": "YouTube",
        "icon": "Youtube",
        "description": "Long and short-form video platform requiring searchable titles, high-retention scripts, and thumbnail concepts.",
        "char_limit": 5000,
        "includes_hashtags": True,
        "recommended_hashtags_count": 5,
        "includes_emojis": True,
        "requires_visual": True,
        "supported_media": ["video", "image", "audio"],
        "content_style": "High CTR clickable title (under 70 chars), 5-second retention hook, structured full video script with scene breakdowns, engaging description with timestamps, tags, thumbnail visual prompt.",
        "best_practices": [
            "Title must trigger intense curiosity or immediate value",
            "First 10 seconds of script must prevent audience drop-off",
            "Include high-contrast thumbnail prompt",
        ],
        "output_requirements": "Catchy title, SEO description, hook, scene-by-scene script, CTA, video tags, thumbnail visual prompt.",
    },
    "linkedin": {
        "id": "linkedin",
        "name": "LinkedIn",
        "icon": "Linkedin",
        "description": "Professional B2B network centered on industry insights, career lessons, and thought leadership.",
        "char_limit": 3000,
        "includes_hashtags": True,
        "recommended_hashtags_count": 4,
        "includes_emojis": False,  # Minimal
        "requires_visual": False,
        "supported_media": ["text", "image", "video"],
        "content_style": "Professional thought-provoking hook line, scannable one-line sentences with whitespace, business takeaway/insights, minimal professional emojis, business CTA, 3-5 industry hashtags.",
        "best_practices": [
            "Line 1 must be a bold statement or contrarian insight",
            "Maintain a polished, authoritative yet approachable tone",
            "Use bullet points for actionable takeaways",
        ],
        "output_requirements": "Professional hook, post body with whitespace, business CTA, 3-5 hashtags (minimal emojis).",
    },
    "twitter": {
        "id": "twitter",
        "name": "X / Twitter",
        "icon": "Twitter",
        "description": "Fast-paced microblogging platform prioritizing punchy takes, threads, and viral hooks.",
        "char_limit": 280,
        "includes_hashtags": True,
        "recommended_hashtags_count": 2,
        "includes_emojis": True,
        "requires_visual": False,
        "supported_media": ["text", "image", "video"],
        "content_style": "Ultra-punchy hook under 280 chars. For longer ideas, build a numbered thread (Tweet 1 / Tweet 2 / ...), high-conviction opinions, crisp CTA.",
        "best_practices": [
            "Never waste words; eliminate filler",
            "Structure threads as numbered tweets (1/X, 2/X...)",
            "Maximum 1-2 hashtags",
        ],
        "output_requirements": "Concise post or numbered thread (Tweet 1, Tweet 2...), punchy CTA, 1-2 hashtags.",
    },
    "whatsapp": {
        "id": "whatsapp",
        "name": "WhatsApp",
        "icon": "MessageCircle",
        "description": "Direct, conversational messenger with bold/italic formatting and immediate personal CTA.",
        "char_limit": 1000,
        "includes_hashtags": False,
        "recommended_hashtags_count": 0,
        "includes_emojis": True,
        "requires_visual": False,
        "supported_media": ["text", "image", "audio"],
        "content_style": "Direct, personalized, conversational messaging using *bold* highlights, emojis, immediate value proposition, direct response CTA with link placeholder.",
        "best_practices": [
            "Sound like a trusted 1-on-1 advisor, not a bulk robot",
            "Use *bold* for key offers or dates",
            "Zero hashtags",
        ],
        "output_requirements": "Personalized direct message, formatted with bold text, emoji cues, zero hashtags, direct reply CTA.",
    },
    "sms": {
        "id": "sms",
        "name": "SMS",
        "icon": "Smartphone",
        "description": "Ultra-concise text messaging under 160 characters with immediate urgency and link CTA.",
        "char_limit": 160,
        "includes_hashtags": False,
        "recommended_hashtags_count": 0,
        "includes_emojis": False,
        "requires_visual": False,
        "supported_media": ["text"],
        "content_style": "Extremely brief (under 160 chars), urgent, personalized hook, value drop, short CTA link placeholder. NO hashtags.",
        "best_practices": [
            "Keep total length under 160 characters",
            "Direct and immediate call to action",
            "Never use hashtags",
        ],
        "output_requirements": "Single concise SMS text (<160 chars) + CTA, strictly NO hashtags.",
    },
    "email": {
        "id": "email",
        "name": "Email Newsletter",
        "icon": "Mail",
        "description": "Direct inbox marketing featuring high-open subject lines, preview text, structured body copy, and clear CTA.",
        "char_limit": 10000,
        "includes_hashtags": False,
        "recommended_hashtags_count": 0,
        "includes_emojis": True,
        "requires_visual": False,
        "supported_media": ["text", "image"],
        "content_style": "High open-rate Subject line (under 50 chars), compelling Preview text, personalized greeting, engaging story/value body copy, bulleted highlights, focused single CTA button text.",
        "best_practices": [
            "Subject line should trigger curiosity or urgent benefit",
            "Preview text supplements the subject line",
            "One primary call to action",
        ],
        "output_requirements": "Subject line, preview text, email body with greeting & sign-off, primary CTA.",
    },
    "blog": {
        "id": "blog",
        "name": "Blog / SEO Article",
        "icon": "BookOpen",
        "description": "Search-optimized long-form content with SEO headlines, meta descriptions, subheadings, and structured sections.",
        "char_limit": 15000,
        "includes_hashtags": False,
        "recommended_hashtags_count": 0,
        "includes_emojis": False,
        "requires_visual": True,
        "supported_media": ["text", "image"],
        "content_style": "SEO-optimized Title with primary keywords, meta description (150-160 chars), compelling Introduction, structured H2/H3 subheadings, comprehensive body paragraphs, actionable summary, final CTA.",
        "best_practices": [
            "Include primary keyword in Title and first 100 words",
            "Break into clear scannable H2/H3 sections",
            "Provide genuine depth and practical advice",
        ],
        "output_requirements": "SEO title, meta description, introduction, structured H2/H3 sections, full body copy, conclusion with CTA, header image prompt.",
    },
}


MEDIA_TYPES: dict[str, dict[str, Any]] = {
    "text": {
        "id": "text",
        "name": "Text & Copywriting",
        "icon": "FileText",
        "description": "Optimized copy, hooks, headlines, body paragraphs, and calls to action.",
        "fields_generated": ["title", "hook", "caption", "body", "cta", "hashtags"],
    },
    "image": {
        "id": "image",
        "name": "Image Visual Prompt",
        "icon": "Image",
        "description": "Downstream prompt engineering for Midjourney / DALL-E / Flux / Stable Diffusion.",
        "fields_generated": ["media_prompt", "image_prompt_details"],
    },
    "video": {
        "id": "video",
        "name": "Video Script & Concept",
        "icon": "Video",
        "description": "Scene-by-scene script, visual cues, camera motion, transitions, and audio directions.",
        "fields_generated": ["video_script", "media_prompt"],
    },
    "audio": {
        "id": "audio",
        "name": "Audio & Voiceover Script",
        "icon": "Mic",
        "description": "Voiceover narrative, tone/emotion cues, speech pacing, and background music suggestions.",
        "fields_generated": ["audio_script"],
    },
}


def get_platform_rules(platform: str) -> dict[str, Any]:
    key = platform.lower().strip()
    if key in PLATFORM_RULES:
        return PLATFORM_RULES[key]
    # Fallback generic rule
    return {
        "id": key,
        "name": key.title(),
        "icon": "Share2",
        "description": f"Content tailored for {key.title()}",
        "char_limit": 2000,
        "includes_hashtags": True,
        "recommended_hashtags_count": 5,
        "includes_emojis": True,
        "requires_visual": False,
        "supported_media": ["text", "image"],
        "content_style": "Engaging, clear hook, valuable body content, clear call to action.",
        "best_practices": ["Keep audience engaged", "Clear CTA"],
        "output_requirements": "Hook, caption, CTA, relevant hashtags.",
    }
